version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    volumes: 
      - ./src/:/app
  
  web:
    build: 
      context: .
      dockerfile: ./docker/web/Dockerfile
    ports:
      - 8080:80
    depends_on:
      - app
    volumes:
      - ./src/:/app

  db:
    build:
      context: .
      dockerfile: ./docker/db/Dockerfile
    ports:
      - 3306:3306
    image: 'mysql:8.0'  
    platform: 'linux/amd64'  
    environment:
      MYSQL_DATABASE: travelers-map
      MYSQL_USER: travelers
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
      TZ: 'Asia/Tokyo'
    volumes:
      - ./docker/db/my.conf:/etc/mysql/conf.d/my.conf
      - mysql-volume:/var/lib/mysql
  
volumes:
  mysql-volume:

